### ISSUE TITLE
WebsafeSvg.string is slow

### ISSUE THREAD

**Issue by rupamking1** [peiffer-innovations/websafe_svg#14]
WebsafeSvg.string is slow please fix it

I have another question - 
WebsafeSvg.asset vs WebsafeSvg.memory vs  WebsafeSvg.string which is fastest.

**Comment by jpeiffer** [comment]
There's nothing for me to fix.  All three are effectively identical to each other, and in fact, WebsafeSvg.string should be the fastest because the others simply utilize that mechanism.

"slow" is relative, and not an issue I've seen in my own uses.  But even if it was, all this package is at its core is a wrapper around `flutter_svg` (for Android / iOS / Desktop) and `Image.network` for web.
