### ISSUE TITLE
Support for precompiled SVGs

### ISSUE THREAD

**Issue by Thioby** [peiffer-innovations/websafe_svg#54]
This library has a dependency to flutter_svg library, that has nice feature. It can show precompiled binary SVG files, which makes whole proces way more faster. 
It would be nice to have the same functionality here in this library.

[Precompiled SVGs](https://pub.dev/packages/flutter_svg#precompiling-and-optimizing-svgs)

**Comment by jpeiffer** [comment]
Oh, nice.  I'm not aware of the same support via the `Image` class which is what this uses for HTML browser rendering.  If you're aware of that capability, let me know and I'll add it in otherwise this wouldn't benefit because this is meant to support both html web, canvas web, and all other platforms via a unified interface.

If you don't need HTML based web, just use the flutter_svg package directly.  With WASM building momentium in Flutter and the HTML approach being more and more recommended against, I suspect the days on this package are numbered.

**Comment by jpeiffer** [comment]
Did not mean to close, just meant to comment.
