### ISSUE TITLE
colorfilter problem

### ISSUE THREAD

**Issue by ahmetveysels** [peiffer-innovations/websafe_svg#8]
The following UnimplementedError was thrown in parseSvgElement:
The <style> element is not implemented in this library.
Style elements are not supported by this library and the requested SVG may not render as intended.
If possible, ensure the SVG uses inline styles and/or attributes (which are supported), or use a
preprocessing utility such as svgcleaner to inline the styles for you.
Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#6f32b(), name:
  "assets/icons/camera-movie.svg", colorFilter: ColorFilter.mode(Color(0xff9e9e9e),
  BlendMode.srcIn))

**Comment by jpeiffer** [comment]
That's an [issue](https://github.com/dnfield/flutter_svg/issues/105) with the underlying `flutter_svg` package this depends on and I believe that was marked as "won't fix" because of the complexities of supporting a full CSS tree.

Using a tool like [svgcleaner](https://github.com/RazrFalcon/svgcleaner) will convert from outer styles to inline styles and in all my test cases, fixed the issue.

You can try to thumbs up or star the underlying issue to ask for a fix.
